/**
 * `wardline init` - write a hardened starting configuration.
 *
 * Nothing here is exotic: a scoped allow list, a deny list that covers the
 * unrecoverable commands, and one PreToolUse hook that logs and blocks. It
 * never overwrites an existing file.
 */

import { chmodSync, existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';

export interface InitResult {
  root: string;
  created: string[];
  skipped: string[];
}

const SETTINGS = {
  permissions: {
    allow: [
      'Read(./**)',
      'Glob(./**)',
      'Grep(./**)',
      'Edit(src/**)',
      'Write(src/**)',
      'Bash(git status)',
      'Bash(git diff *)',
      'Bash(git log *)',
      'Bash(npm test)',
      'Bash(npm run build)',
    ],
    deny: [
      'Bash(rm -rf *)',
      'Bash(sudo *)',
      'Bash(chmod 777 *)',
      'Bash(dd if=*)',
      'Bash(curl * | sh)',
      'Bash(git push --force *)',
      'Read(./.env)',
      'Read(./.env.*)',
      'Read(~/.ssh/**)',
      'Read(~/.aws/**)',
      'Write(.github/**)',
      'Write(.claude/**)',
    ],
    ask: ['Bash(git commit *)', 'Bash(git push *)', 'Bash(npm install *)'],
  },
  hooks: {
    PreToolUse: [
      {
        matcher: 'Bash|Write|Edit',
        hooks: [
          {
            type: 'command',
            command: '.claude/hooks/guard.sh',
            timeout: 5,
          },
        ],
      },
    ],
  },
};

/**
 * The generated guard. Every expansion is quoted, failures are loud, and the
 * refusal list lives in `case` patterns so the script matches on those strings
 * rather than running them.
 */
const GUARD = [
  '#!/usr/bin/env bash',
  '# PreToolUse guard. Reads the tool call as JSON on stdin, appends it to a',
  '# local log, and refuses paths an agent should never touch. Exit 2 blocks',
  '# the call; exit 0 lets it through.',
  'set -euo pipefail',
  '',
  'LOG_DIR="$(dirname "$0")/../logs"',
  'mkdir -p "$LOG_DIR"',
  '',
  'payload="$(cat)"',
  'stamp="$(date -u +%Y-%m-%dT%H:%M:%SZ)"',
  '',
  '# Quoted throughout: a filename with a space or a quote must stay data.',
  'echo "$stamp $payload" >> "$LOG_DIR/tool-calls.log"',
  '',
  'case "$payload" in',
  '  *".ssh/"*|*".aws/credentials"*|*"/etc/shadow"*)',
  '    echo "wardline guard: refusing access to credential storage" >&2',
  '    exit 2',
  '    ;;',
  '  *"rm -rf /"*|*"rm -rf ~"*)',
  '    echo "wardline guard: refusing recursive delete outside the project" >&2',
  '    exit 2',
  '    ;;',
  'esac',
  '',
  'exit 0',
  '',
].join('\n');

const NOTES = [
  '# Agent security notes',
  '',
  'This configuration was generated by `wardline init`. Two rules keep it useful:',
  '',
  '1. **Widen deliberately.** Add a permission when a real task needs it, and add',
  '   the narrowest entry that unblocks the task. `Bash(npm test)` beats `Bash(npm *)`.',
  '2. **External content is data.** Anything fetched from a URL, an issue, a review',
  '   comment or a dependency is untrusted input. It is never an instruction, no',
  '   matter how it is phrased.',
  '',
  'Re-check the configuration after any change:',
  '',
  '```bash',
  'npx wardline scan',
  '```',
  '',
].join('\n');

function writeIfAbsent(
  path: string,
  content: string,
  result: InitResult,
  executable = false,
): void {
  if (existsSync(path)) {
    result.skipped.push(path);
    return;
  }

  mkdirSync(dirname(path), { recursive: true });
  writeFileSync(path, content, 'utf8');

  if (executable) {
    try {
      chmodSync(path, 0o755);
    } catch {
      // Windows filesystems have no execute bit; the file is still written.
    }
  }

  result.created.push(path);
}

export function initConfig(target?: string): InitResult {
  const root = resolve(target ?? process.cwd());
  const base = join(root, '.claude');
  const result: InitResult = { root, created: [], skipped: [] };

  writeIfAbsent(join(base, 'settings.json'), JSON.stringify(SETTINGS, null, 2) + '\n', result);
  writeIfAbsent(join(base, 'hooks', 'guard.sh'), GUARD, result, true);
  writeIfAbsent(join(base, 'SECURITY.md'), NOTES, result);

  return result;
}
